### ISSUE TITLE
How to install fsynth on Arch linux?

### ISSUE THREAD

**Issue by yagarea** [grz0zrg/fsynth#15]
Is there any official way to install fsynth on arch linux ?

Thank you for help

**Comment by grz0zrg** [comment]
Not as a pre-made package, the only one available is a .deb.

Maybe there is some working solution such as using `debtap` to convert the deb package to Arch linux one but this is untested.

The latest client is simple to install by following this and replacing the `apt install` command by the Arch linux one (Pacman ?) :

https://github.com/grz0zrg/fsynth#how-to-setup-your-own-server

However you will also need the audio server since web. audio client was dropped some times ago (it should be simple but not as simple as running 2-3 commands)  : https://github.com/grz0zrg/fas#build

Might see how i can provide better compatibility for the audio server binary on the next release. (such as Appimage)

**Comment by grz0zrg** [comment]
There is now AppImage on the Fragment homepage.
